# Generated by Django 4.0.6 on 2022-07-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_basketitem_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
