# Generated by Django 4.0.6 on 2022-07-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_promocode_discount_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='discount_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_type',
            field=models.CharField(choices=[('%', 'percent'), ('-', 'sum')], default='%', max_length=10),
        ),
    ]
